


bench:
	hyperfine -N --warmup 10 'go/main' 'node js/main.js'  'lua lua/main.lua'  'zig/main' 'c/main' 'go/main' 'cpp/main' 'zig/main'


# hyperfine -N --warmup 10 'go/main' 'node js/main.js' 'zig/main' 'c/main'

# --warmup 3 'grep -R TODO *'

